### ISSUE TITLE
deduplicate jcom jars

### ISSUE THREAD

**Issue by carlschroedl** [happyjack27/autoredistrict#10]
There are two nearly identical jars in the project:
`jcom.jar`
and
`src/excel/jcom_new.jar`

![There Can Be Only One](http://img.picturequotes.com/2/2/1830/there-can-be-only-one-quote-2.jpg)

;)

I listed the contents of both jars by running:
```
unzip -l src/excel/jcom_new.jar > jcom_new.jar.list
unzip -l jcom.jar > jcom.jar.list
```

Then printed the column headers and the associated diff by running:
```
head -n 3 jcom.jar.list | tail -n 2
diff jcom.jar.list jcom_new.jar.list
```

Which yields:
```
Length      Date    Time    Name
---------  ---------- -----   ----
1c1
< Archive:  jcom.jar
---
> Archive:  src/excel/jcom_new.jar
24c24
<      3452  2004-05-31 02:42   jp/ne/so_net/ga2/no_ji/jcom/IDispatch.class
---
>      4387  2013-09-05 14:12   jp/ne/so_net/ga2/no_ji/jcom/IDispatch.class
41c41
<     67220                     36 files
---
>     68155                     36 files
```

So, the files within the jar are nearly all the same except for IDispatch.class, which had a bigger version of added to the new jar in 2013. Any idea which one we prefer?

**Comment by happyjack27** [comment]
the jcom.jar one.  delete jcom_new.jar

btw, it doesn't work.  complains about 32-bit vs 64-bit. :P
a different excel solution might be nice but everything else i found was
bloated.
was also thinking of a button on the stats page to create an html page of
the map and open it in a browser.
should have a stylsheet in resources, and copy that over along w/ images
and stuff to %profil%/autoredistrict_data/[stare]/...
