### ISSUE TITLE
Enable a Continuous Integration Service

### ISSUE THREAD

**Issue by carlschroedl** [happyjack27/autoredistrict#12]
Weee! Let's try this in Agile User Story Format:
As a X I want Y so that Z.

As a maintainer of autoredistrict I want to enable a continuous integration service like [travis ci](https://travisci.com) so that I know that the project's master branch currently builds in a clean-slate environment.

As a maintainer of autoredistrict reviewing a pull request I want a continuous integration service to test if the pull request breaks the build so that I can refrain from looking at it too closely until it builds.

As a contributor to autoredistrict I want a continuous integration service to test if my pull request breaks the build so that I receive automatic feedback on whether my contributions would break the build and can react accordingly without waiting for maintainers to pull down my proposed pull request and run the tests themselves.

**Comment by happyjack27** [comment]
i guess i don't see why we need this.

**Comment by carlschroedl** [comment]
By 'this' do you mean Travis or CI in general? If it's Travis, I'm open to learning about other options. If it's CI in general, look at any site that details contemporary software engineering best practices. One example from Uncle Bob Martin:
http://www.martinfowler.com/articles/continuousIntegration.html

**Comment by happyjack27** [comment]
CI in general.

i can see the benefit for very large projects, with a whole bunch of members.  but that's not the case here.  it's not needed, nothing's broken.  if it ain't broke, don't fix it.

make sure it builds before you push it.  easy enough to do with auto-compiling ide's.  if i have to merge, i'll make sure it builds.  worst case if it doesn't build for a while, not a big deal, it's not a release version.  could track down the issues and fix in a matter of minutes.

**Comment by happyjack27** [comment]
k, it's integrated.  if there's anything that still needs to be done, do it if u can or let me know if i need to.  or close if we're all set.
