### ISSUE TITLE
NullPointerException attempting to load /resources/geoheader_cols.txt

### ISSUE THREAD

**Issue by elvo86** [happyjack27/autoredistrict#164]
Hello!

I downloaded this project and built it, but ran into a problem downloading the data to use it. I selected File > Download vtd shapefile & population from census.gov... and chose my home state of New York. The downloads were successful, and the checks were good. But then the tool moved on to extracting the demographics data and the app crashed with the following message:
```
unzipping /Users/elliot/autoredistrict_data/New York/2010/demographics/ny2010.pl.zip
extracting /Users/elliot/autoredistrict_data/New York/2010/demographics//nygeo2010.pl...
extracting /Users/elliot/autoredistrict_data/New York/2010/demographics//ny000012010.pl...
extracting /Users/elliot/autoredistrict_data/New York/2010/demographics//ny000022010.pl...
extracting /Users/elliot/autoredistrict_data/New York/2010/demographics//ny2010.pl.prd.packinglist.txt...
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at util.Util.readStream(Util.java:1242)
	at ui.MainFrame$ImportDemographics.getDemographics(MainFrame.java:7311)
	at ui.MainFrame$ImportDemographics.run(MainFrame.java:7204)
```

Looking at the code in MainFrame.java, it can't find `/resources/geoheader_cols.txt`. In fact, I see there are several references in the code to a `resources` folder, but there is no such folder. I also see hardcoded paths to your local filesystem, putting a resources folder inside the bin folder. Do you have some required resources gitignored?

**Comment by happyjack27** [comment]
looks like i do.

will check when i get home.

thanks for the catch.

**Comment by happyjack27** [comment]
it's there.

the file's right here: https://github.com/happyjack27/autoredistrict/blob/master/src/resources/geoheader_cols.txt

and the folder is here:
https://github.com/happyjack27/autoredistrict/tree/master/src/resources

must be something with how you're building it.

**Comment by elvo86** [comment]
That's strange... I built it using `./build.sh`.

Thanks!

**Comment by happyjack27** [comment]
i didn't write build.sh, another programmer did.  i guess he didn't
thoroughly test it.  i just launch it straight out of eclipse.

feel free to send in corrections.
