### ISSUE TITLE
Where is the JAR?

### ISSUE THREAD

**Issue by pawod** [happyjack27/autoredistrict#168]
Readme says there is a `autoredistrict.jar` in the `jar` dir, but it's not.

**Comment by happyjack27** [comment]
Somehow didn't see this in my email.

For the jar you can either just download the latest release, or "export to jar" via your IDE.   If I remember right offhand, ui.Applet is the main class.

But yeah - this is a note to self - I'll try to make sure the jar's there in my next commit.   I might have put it as .gitnore.
