### ISSUE TITLE
Errors at compilation

### ISSUE THREAD

**Issue by bixiou** [happyjack27/autoredistrict#203]
Two errors appear when I compile:

`src/geography/Project.java:103: error: cannot find symbol
			MainFrame.mainframe.textField.setText(getString("initial_population").trim());
			                   ^
  symbol:   variable textField
  location: variable mainframe of type MainFrame
src/geography/Project.java:104: error: cannot find symbol
			MainFrame.mainframe.textField.postActionEvent();
			                   ^
  symbol:   variable textField
  location: variable mainframe of type MainFrame
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
`

**Comment by happyjack27** [comment]
how are you building/compiling?

what's your ide? (or are you doing command line?)

what jdk version?

**Comment by bixiou** [comment]
My bad, I forgot to install jdk.
