### ISSUE TITLE
Auto-Redistrict FTP Links All Dead

### ISSUE THREAD

**Issue by gawhaley** [happyjack27/autoredistrict#209]
FTP links like the one below all return error "550: failed to change directory."

ftp://autoredistrict.org/pub/shapefiles2/Ohio/2010/2012/vtd/

Not a lot of experience with FTP - is this an error on my end?

**Comment by happyjack27** [comment]
that link is wrong.  the ftp stie is here:

ftp://autoredistrict.org/pub/
