### ISSUE TITLE
jcom doesn't work - complains mix of 32-bit with 64-bit

### ISSUE THREAD

**Issue by happyjack27** [happyjack27/autoredistrict#32]
jcom doesn't work - complains mix of 32-bit with 64-bit
i know it would work, 'cause i tested it outside of autoredistrict.
anycase might need to look for a different lightweight export to excel solution.

**Comment by carlschroedl** [comment]
oops inadvertently closed

**Comment by carlschroedl** [comment]
open

**Comment by happyjack27** [comment]
closing this as won't fix.  the excel export functionality has been removed and favor of html export
